INSERT INTO PREVILEGES (PREVILEDGEID, User) VALUES (0, 'Admin');
INSERT INTO PREVILEGES (PREVILEDGEID, User) VALUES (1, 'HeadMaster');
INSERT INTO PREVILEGES (PREVILEDGEID, User) VALUES (2, 'HeadOfDept');
INSERT INTO PREVILEGES (PREVILEDGEID, User) VALUES (3, 'Teacher');